# Generated by Django 5.1.3 on 2024-11-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rcp_5d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rfid_number',
            field=models.IntegerField(unique=True),
        ),
    ]
